# Generated by Django 3.1.5 on 2021-01-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listatarefas',
            name='descricao',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listatarefas',
            name='realizada',
            field=models.BooleanField(null=True),
        ),
    ]
